{
 "title": "Jellyseerr",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Request Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jellyseerr_requests_count)", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "Requests by Media Type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (media_type))",
     "legendFormat": "{{ media_type }}"
    }
   ]
  },
  {
   "title": "Request Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Approved\"})",
     "legendFormat": "Approved "
    },
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Declined\"})",
     "legendFormat": "Declined"
    }
   ]
  },
  {
   "title": "Request Availability",
   "type": "stat",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Available\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Part-Available\"})",
     "legendFormat": "Part-Available"
    },
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Processing\"})",
     "legendFormat": "Processing"
    }
   ]
  },
  {
   "title": "Media Type Count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (media_type))",
     "legendFormat": "{{ media_type }}"
    }
   ]
  },
  {
   "title": "Media Type Count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (is_4k))",
     "legendFormat": "{{ media_type }}"
    }
   ]
  },
  { "title": "Request Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Requests by User",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(jellyseerr_user_requests) > 0 ",
     "legendFormat": "{{ email }}"
    }
   ]
  },
  {
   "title": "Request Genres",
   "type": "piechart",
   "description": "The genres requested",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (genre))",
     "legendFormat": "{{genre}}"
    }
   ]
  }
 ]
}